version: 2.1

executors:
  python3-executor:
    docker:
      - image: circleci/python:3.6

jobs:

  syntax-checks:
    executor: python3-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install flake8

      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 --exclude venv --max-line-length=100 --extend-ignore=E203 --show-source

      - run:
          name: Check critical errors
          command: |
            . venv/bin/activate
            flake8 --exclude venv --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  
  # Unit test and code coverage
  unit-tests:
    executor: python3-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            pip3 install pytest coverage
      - run:
          name: Run tests and coverage
          command: |
            . venv/bin/activate
            coverage run --source=credit_models/ -m pytest -v --tb=line tests/
            coverage report
            coverage html

      - store_artifacts:
          path: htmlcov


workflows:
  version: 2
  code-quality-and-unit-test:
    jobs:
      - syntax-checks
      - unit-tests:
          requires:
            - syntax-checks


